# Generated by Django 5.1.4 on 2026-07-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Niketa', max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chef/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chef profile',
                'verbose_name_plural': 'Chef profile',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram')], default='INSTAGRAM', max_length=12)),
                ('handle', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='chef.chefprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
