# Generated by Django 5.1.4 on 2026-07-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PAYMENT_SUBMITTED', 'Payment submitted'), ('PAYMENT_REJECTED', 'Payment rejected'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor_label', models.CharField(max_length=60)),
                ('reason', models.CharField(blank=True, max_length=140)),
                ('customer_stage', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intent', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proofs/')),
                ('is_current', models.BooleanField(default=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('decided_by', models.CharField(blank=True, max_length=60)),
                ('reject_reason', models.CharField(blank=True, max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='orders.order')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
