# Generated by Django 5.1.4 on 2026-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_orderevent_paymentintent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfil_mode',
            field=models.CharField(choices=[('ORDER_NOW', 'Order now'), ('ORDER_FOR_LATER', 'Order for later')], default='ORDER_NOW', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
