# Generated by Django 5.1.4 on 2026-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chef_style_platform',
            field=models.CharField(blank=True, default='INSTAGRAM', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef_style_url',
            field=models.URLField(blank=True),
        ),
    ]
