# Generated by Django 5.1.4 on 2026-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_recipe_chef_style_platform_recipe_chef_style_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ordering_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
