# Generated by Django 5.1.4 on 2026-07-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_recipe_ordering_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='default_accompaniment',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
