# Generated by Django 5.1.4 on 2026-07-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_recipe_default_accompaniment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video (opens out)'), ('LINK', 'Link (opens out)')], default='IMAGE', max_length=8)),
                ('file', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='menu.recipe')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
